added unit test for density kernel
sphexa-org/sphexa pull request #105
Opened 2021-10-15 11:56 UTC by sekelle

2021-10-15 12:53 UTC, jgphpc requested changes
temporary blocking merge to give me some time to validate/debug the ci (I will unlock when ready).

2021-10-15 14:18 UTC, rmcabezon requested changes

2021-10-15 14:18 UTC, rmcabezon commented on include/sph/test/kernel/density.cpp
> +     *
With these distances and h(0)=5, all particles will be neighbors. I'd recommend using a smaller h so that some particles are neighbors and others are not. In that way, you ensure also that the kernel is adding a zero when a particle is qualified as a neighbor but in fact, is not. This might happen if we define the neighborhood with a gather models instead of a scatter model.

2021-10-15 14:18 UTC, rmcabezon commented on include/sph/test/kernel/density.cpp
> +    /* distances of particle 0 to particle j
Same comment as above. Either reduce h(0) or add some particles farther than 2h(0).

2021-10-15 18:00 UTC, sekelle commented on include/sph/test/kernel/density.cpp
> +     *
The current implementation of the density kernel assumes that the neighbor list is correct. Whatever is listed as a neighbor will be added, even if the distance turns out to be bigger than 2*h. So I can't really test correct neighbor search here.

2021-10-15 18:07 UTC, sebkelle1 commented
@jgphpc This MR need not be held up just because the test is not in the CI yet. You can add it to the CI in a separate MR.

2021-10-16 13:22 UTC, jgphpc approved these changes
[  PASSED  ] Ran 7/8 test case(s) from 8 check(s) (0 failure(s), 1 skipped)
Will add new unittest after merging.

2021-10-18 06:37 UTC, rmcabezon approved these changes

2021-10-18 18:32 UTC, merged

2021-10-18 18:39 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 31/32 test case(s) from 32 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13401 github_pr=105
fa8c245