Optimize density
sphexa-org/sphexa pull request #106
Opened 2021-10-15 13:39 UTC by sekelle

This is mostly cleanup, performance on the CPU improves a bit, but stays the same on the GPU.

2021-10-15 14:28 UTC, rmcabezon requested changes
I don't know what the variable ltsize does or why has been removed. I assume that is obsolete.

2021-10-15 14:28 UTC, rmcabezon commented on include/sph/kernel/computeDensity.hpp
> +    T volumeInv = hInv * hInv * hInv;
Indeed this is a volume, but I'm afraid that if we call it this way it will be confusing with the volume elements.  Maybe h3Inv or hVolumeInv, to clarify that this is related to h and nothing else.

2021-10-15 14:28 UTC, rmcabezon commented on include/sph/kernel/computeIAD.hpp
>          const T W = w / (h[i] * h[i] * h[i]);
This h3 inverse can also be taken out of the j-loop, as for the density.

2021-10-15 14:28 UTC, rmcabezon commented on include/sph/kernel/computeIAD.hpp
>          const T vloc = dist / h[i];
Same optimization as for the density here is possible.

2021-10-15 14:28 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>          const T W1 = w1 / (h[i] * h[i] * h[i]);
Same optimization for K and 1./h3 as for density is possible here.

2021-10-16 13:46 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 31/32 test case(s) from 32 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13387 github_pr=106
17eef9c

2021-10-16 13:47 UTC, jgphpc approved these changes
ci passed, will add new test after merging.

2021-10-18 19:36 UTC, sekelle commented on include/sph/kernel/computeDensity.hpp
> +    T volumeInv = hInv * hInv * hInv;
sure, will do

2021-10-18 19:38 UTC, sekelle commented on include/sph/kernel/computeIAD.hpp
>          const T vloc = dist / h[i];
This function is not tested yet. Will introduce the optimization and tests in a separate PR.

2021-10-18 19:38 UTC, sekelle commented on include/sph/kernel/computeIAD.hpp
>          const T W = w / (h[i] * h[i] * h[i]);
This function is not tested yet. Will introduce the optimization and tests in a separate PR.

2021-10-18 19:38 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>          const T W1 = w1 / (h[i] * h[i] * h[i]);
This function is not tested yet. Will introduce the optimization and tests in a separate PR.

2021-10-19 07:21 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13404 github_pr=106
7d6c71d

2021-10-19 07:48 UTC, rmcabezon approved these changes

2021-10-19 11:17 UTC, merged