Cmake fix
sphexa-org/sphexa pull request #107
Opened 2021-10-18 13:13 UTC by biddisco

A couple of minor cmake fixes to get it building locally

2021-10-18 20:17 UTC, jgphpc commented
```
[  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped)
```

2021-10-18 20:19 UTC, jgphpc approved these changes

2021-10-19 11:45 UTC, sekelle requested changes

2021-10-19 11:45 UTC, sekelle commented on src/evrard/CMakeLists.txt
> +find_library(CUDART_LIBRARY cudart ${CMAKE_CUDA_IMPLICIT_LINK_DIRECTORIES})
Let's add `find_package(CUDAToolkit)` just after we enable the CUDA language. Then we can
link applications against `CUDA::cudart` and omit adding the include dirs explicitly.

2021-10-19 16:39 UTC, biddisco commented on src/evrard/CMakeLists.txt
> +find_library(CUDART_LIBRARY cudart ${CMAKE_CUDA_IMPLICIT_LINK_DIRECTORIES})
I actually tried that, but for reasons I didn't want to spend (waste) time trying to understand, `find_package(CUDAToolkit)` didn't work on my laptop, so I left it as find library for now. I might have made a silly typo or something and should try again really.

2021-10-27 10:02 UTC, sekelle commented
superseded by #109

2021-10-27 10:02 UTC, closed without merging