Kernel clean
sphexa-org/sphexa pull request #111
Opened 2021-10-27 13:43 UTC by sekelle

clean and simplify IAD kernel

2021-10-28 10:17 UTC, rmcabezon requested changes

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeIAD.hpp
> +    T hi3    = hi * hi * hi;
You actually don't need the variable hi3. You can plug this in directly in factor.

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeIAD.hpp
> +    T factor = hi3 / (det * K);
Maybe add a comment on top of this clarifying that cij elements have units of 1/tau because det has units of tau^3, so we have to divide by K/h^3 to get the normalization factor correctly.
Otherwise, if someone checks this later, might wrongly think this should be multiplying.

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
> +        T rz    = (z[j] - zi);
Better keep the other one rx=(xi - x[j]). The standard way of writing the equations in SPH is i - j
I know we have to use for a few equations -rx later, but if we add more SPH equations here, we might inadvertely use rx with the wrong sign. Of course, this is extensive to ry and rz.

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
> +        const T rv = -(rx * v_ijx + ry * v_ijy + rz * v_ijz);
Changing rx, ry, and rz as mentioned above eliminates this minus sign.

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
> +        const T W1 = w1 / (hi * hi * hi);
You can calculate hi^3 outside of the j-loop.

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>          const T pro_j = p[j] / (gradh_j * ro[j] * ro[j]);
pro_i and pro_j can be calculated at the EOS directly and divide by gradh  in the subroutine where gradh has been calculated so that pro_i and pro_j don't need to be calculated here. They are fully local values that don't depend of any neighbor to be calculated. What I typically do is calculate pro in the EOS and divide it by gradh in the momentum equation.

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>          if (vijsignal > maxvsignali) maxvsignali = vijsignal;
This if condition can be substituted with a max function: maxvsignali=max(maxvsignali, vijsignal)

2021-10-28 10:17 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
With the change of rx, ry, and rz, all these should have a minus multiplying.

2021-10-28 10:47 UTC, jgphpc approved these changes

2021-10-28 10:55 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13459 github_pr=111
53e87f1

2021-10-28 11:20 UTC, sekelle commented on include/sph/kernel/computeIAD.hpp
> +    T hi3    = hi * hi * hi;
done

2021-10-28 11:20 UTC, sekelle commented on include/sph/kernel/computeIAD.hpp
> +    T factor = hi3 / (det * K);
done

2021-10-28 11:20 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
done

2021-10-28 11:24 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>          const T pro_j = p[j] / (gradh_j * ro[j] * ro[j]);
gradh_i and grad_j are constants equal to 1.0 here...
if you calculate pro_i and pro_j in the EOS, then where do you store it?

2021-10-28 11:25 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13460 github_pr=111
1fbdf6b

2021-10-28 11:25 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>          if (vijsignal > maxvsignali) maxvsignali = vijsignal;
I don't have a portable max function at this point here that works in both CPU and GPU code.
I might add one later. For now, I'm using a ternary statement. Almost as short.

2021-10-28 11:36 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13461 github_pr=111
3f2040c

2021-10-28 11:43 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13462 github_pr=111
fc0324f

2021-10-28 12:04 UTC, rmcabezon requested changes

2021-10-28 12:04 UTC, rmcabezon commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>      maxvsignal[i] = maxvsignali;
Maybe add a comment before this lines to state why we add a minus here. Otherwise, we will forget.

2021-10-28 12:52 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
> +        T rz    = (z[j] - zi);
done

2021-10-28 12:52 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
> +        const T rv = -(rx * v_ijx + ry * v_ijy + rz * v_ijz);
done

2021-10-28 13:00 UTC, sekelle commented on include/sph/kernel/computeMomentumAndEnergy.hpp
>      maxvsignal[i] = maxvsignali;
done

2021-10-28 13:04 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 33/34 test case(s) from 34 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13464 github_pr=111
ac5e6a8

2021-10-29 09:42 UTC, rmcabezon approved these changes

2021-10-29 12:02 UTC, merged

2021-10-29 12:19 UTC, jgphpc commented
Check gitlab tests results before merging: [  PASSED  ] Ran 39/40 test case(s) from 40 check(s) (0 failure(s), 1 skipped) https://git.scicore.unibas.ch/j.piccinali/mirror_test/-/pipelines/13474 github_pr=111
3070474