VE fusion
sphexa-org/sphexa pull request #230
Opened 2022-04-27 20:22 UTC by jaescartin1

VE added to the normal execution

2022-04-28 08:54 UTC, sebkelle1 requested changes
We will be able to use the individual parts of this PR, but we'll have to apply these changes incrementally:
1. introduce grad-h terms
2. modernize GPU particles data
3. change filenames to make VE the default for the CPU
4. introduce cuda ve implementation from this PR

For the moment I still need the old kernels for testing and debugging non-SPH parts of the code, but they can be made non-default to avoid interfering with work on the newer versions.

2022-04-28 09:45 UTC, realnewton approved these changes
Very necessary homogenization of the names of the functions, elimination of the standard old-fashion SPH and implementation of cuda VE. I only added a few suggestions that can be addressed in subsequent PRs.

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/propagator.hpp
> +        CHECK_CUDA_ERR(cudaMemcpy(d.devPtrs.d_x, d.x.data(), size_np_T, cudaMemcpyHostToDevice));
As a suggestion to clean this a bit out in the future: these copies could be added in a single function (f.e. Host2Device) that takes the different fields as inputs. Then we can have a single line instruction while still keeping explicitly written the data that is being transferred.

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/propagator.hpp
> +#ifdef USE_CUDA
Suggestion for future upgrade: this structure of copy to host - MPI sync - copy back to the device, could also be included inside of the exchangeHalos function and clean it out from the propagator, as it appears many times.

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/propagator.hpp
> +        if (d.g == 0)
Why do we use g==0 as condition here if we also have doGrav boolean?

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/propagator.hpp
> +        }
These copies to host are done, no matter we have gravity or not. They can be moved out of the if condition down to after gravity is calculated.

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/propagator.hpp
>              mHolder_.upsweep(d, domain);
We should add here a comment stating that gravity modifies gradP adding the gravitational forces.

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/sphexa.cpp
> +    if (haveGrav)
Yet another boolean for gravity calculation (g=0, doGrav, haveGrav). We should normalize this.

2022-04-28 09:45 UTC, realnewton commented on main/src/sphexa/sphexa.cpp
> +    totalTimer.step("Total execution time of " + std::to_string(d.iteration - startIteration) + " iterations of " +
Shouldn't the +1 be here? When iteration = startIteration that would give zero instead of 1.

2022-04-28 09:45 UTC, realnewton commented on sph/include/sph/cuda/gpu_particle_data.cuh
> +    // Number of CUDA streams to use
Probably number of streams (NST) and taskSize should also go to CudaConfig.

2022-04-28 09:45 UTC, realnewton commented on sph/include/sph/cuda/gpu_particle_data.cuh
> +struct CudaConfig
This CudaConfig should be somewhere else more exposed to the user.

2022-04-28 09:51 UTC, realnewton commented
I agree with the steps suggested by Sebastian, but only if these don't take forever. The next test in line will need high-particle count and VE to work. I will do the gradh PR asap, so please keep this moving forward with high priority. Otherwise, we will be stuck in the tests and facing constant merge conflicts.

2022-04-28 10:10 UTC, jaescartin1 commented
I am agree with Sebastian too. Please, feel free to apply the plan.

Like I am done with the VE fusion, because this PR works (adding the little changes for improve that both of you suggested for improve it), I will move to the implementation of the "Wind-cloud collision" test where we need VE and a minimum of 4 million of particles (here GPU execution is almost mandatory).

2022-05-20 16:32 UTC, sebkelle1 commented
Addressed here: https://github.com/unibas-dmi-hpc/SPH-EXA/pull/265

2022-05-20 16:32 UTC, closed without merging