Mach RMS calculations for turbulence runs
sphexa-org/sphexa pull request #341
Opened 2022-12-07 09:17 UTC by lks1248

2022-12-07 14:38 UTC, sekelle requested changes

2022-12-07 14:38 UTC, sekelle commented on main/src/observables/conserved_gpu.cu
> +        const Tm* m, const Tc* c, size_t, size_t)
This should be disentangled here to have some flexibility and options to compose different observable.
The mach numbers should be handled with a separate function here.
What you can reuse/extend for now are the `conserved_gpu` files and the `computeConservedQuantities` where the MPI reduction happens.

2022-12-07 14:38 UTC, sekelle commented on main/src/observables/conserved_quantities.hpp
> +        machSum += norm2(V) / (c[i]*c[i]);
Also the CPU should do this computation in a separate function.

2022-12-08 08:14 UTC, realnewton reviewed
The calculation is correct, but I would use Mach2 or MachSq whenever necessary (localsum, local values, etc...) to be clear that what we are calculating is in fact the squared value of the Mach number. I only pointed this on the first file, but if corrected, needs to be done in the other files, too. 
Not for MachRMS. That's correct.

2022-12-08 08:14 UTC, realnewton commented on main/src/observables/conserved_gpu.cu
> +struct MachSum
I would call this Mach2Sum or MachSqSum, as we are in fact calculating the squared value of the Mach number.

2022-12-08 08:14 UTC, rmcabezon commented on main/src/observables/conserved_gpu.cu
> +    auto localMachSum = 0.0;
Same as above. localMach2Sum or localMachSqSum

2022-12-08 08:14 UTC, rmcabezon commented on main/src/observables/conserved_gpu.cu
> +double machSumGpu(const Tv* vx, const Tv* vy, const Tv* vz, const Tc* c, size_t first, size_t last)
Same as above. Mach2SumGpu or MachSqSumGpu.

2022-12-09 09:22 UTC, sekelle approved these changes

2022-12-09 09:22 UTC, merged