Execute Grackle cooling in OMP blocks. Convert Xmass to density in computeDensity instead of in eos.
sphexa-org/sphexa pull request #434
Opened 2024-01-18 15:02 UTC by nknk567

2024-02-12 13:41 UTC, sekelle commented
I added a missing OpenMP loop and replaced a cuda kernel with thrust::transform.
Other than that I noticed the following points:

* Interface duplication: Your new interface is more powerful and flexible. Passing `numParticles=1` corresponds to the old interface to cool a single particle. Is there any reason to keep the old interface instead of e.g. only exposing
```c++
void cool_particles(T dt, const T* rho, const T* u, T* du, const ParticleType& firstParticle, Tvec2& du, std::size_t numParticles);
```?
This would also allow you to get rid of the old `struct cooler_field_data_content` and you wouldn't need a nearly duplicate test. It's a fair amount of non-trivially maintainable code, so these simplifications would be non-negligible.
* The tasking logic is implemented in the facade and thus exposed to the rest of the code, but could/should be internal to the your GRACKLE frontend.

2024-02-19 18:05 UTC, sekelle requested changes

2024-02-19 18:05 UTC, sekelle commented on physics/cooling/include/cooling/cooler_impl.hpp
> +            convertFracToDens(particle, rho, b);
I can "forget" to do the conversion from fractions to densities, either here or below by commenting the conversion, and the grackle cooling tests still pass!

2024-02-26 13:49 UTC, nknk567 commented on physics/cooling/include/cooling/cooler_impl.hpp
> +            convertFracToDens(particle, rho, b);
Rho was = 1 in the test. Test was updated.

2024-03-06 13:43 UTC, sekelle approved these changes

2024-03-06 13:43 UTC, merged