ParticleID
sphexa-org/sphexa pull request #452
Opened 2024-08-27 13:53 UTC by OsmanSeckinSimsek

Initialise the particle IDs at the beginning of the simulation. the id field is conserved throughout the simulation, but does not change during the execution.

2024-09-16 07:03 UTC, sekelle requested changes
Please rebase on develop and squash into a single commit once done.

2024-09-16 07:03 UTC, sekelle commented on main/src/init/evrard_init.hpp
> +
`generateParticleID` just initializes an additional field. It can be called in `initEvrardFields` where all the other fields are initialized as well. Same for the other test cases.

2024-09-16 07:03 UTC, sekelle commented on main/src/init/utils.hpp
> +void generateParticleIDs(Dataset& d, int rank, int numRanks)
This function doesn't need the full dataset, only a `std::span<uint64_t> id` . At the call site `d.id` can be passed, which will either have size 0 if ids are (temporarily) disabled or have size `numLocalParticles`.

2024-09-16 07:03 UTC, sekelle commented on main/src/init/utils.hpp
> +    std::vector<size_t> ranksLocalParticles(numRanks);
use `uint64_t` here to avoid compatibility issues with MacOS

2024-09-16 07:03 UTC, sekelle commented on main/src/init/utils.hpp
> +    MPI_Allgather(&localNumRanks, 1, MPI_UNSIGNED_LONG, ranksLocalParticles.data(), 1, MPI_UNSIGNED_LONG,
use `MpiType<uint64_t>{}` here instead of MPI_UNSIGNED_LONG

2024-09-16 07:03 UTC, sekelle commented on main/src/init/utils.hpp
> +    }
These `for` loops are equivalent to:
```c++
std::exclusive_scan(ranksLocalParticles.begin(), ranksLocalParticles.end(), ranksLocalParticles.begin(), uint64_t(0));
std::iota(id.begin(), id.end(), ranksLocalParticles[rank]);
```
This will work also if `id` is not actually allocated, which is needed if we want to make it an optional feature later or temporarily disable it by removing `id` from the list of conserved fields.

2024-09-17 13:30 UTC, OsmanSeckinSimsek commented on main/src/init/evrard_init.hpp
> +
this requires passing rank and numRanks to the init*Fields functions. Should I pass these parameters as well?

2024-09-19 15:35 UTC, sekelle commented on main/src/init/evrard_init.hpp
> +
You're already using the MPI communicator in `generateParticleIDs`. Might as well use it to obtain `rank` and `numRanks` as well. You can take the communicator as an argument to `generateParticleIDs` and pass `MPI_COMM_WORLD` at the call site. (One less function to remove `MPI_COMM_WORLD` from later).

2024-10-25 12:30 UTC, sekelle commented
Addressed in a follow-up PR

2024-10-25 12:30 UTC, closed without merging