Implement physics for protoplanetary disks / TDEs
sphexa-org/sphexa pull request #466
Opened 2024-11-11 18:58 UTC by nknk567

- Physics for protoplanetary disk (central star, accretion, beta cooling).
- Changed computeGravity to also get the potential of each particle
- Equation of state now works with both T or u
- Additional polytropic equation of state added for TDE

minor changes:

- added a header in data_util.hpp and field_states.hpp
- added instantiation for Trho equal to double in Grackle cooler

2024-12-08 15:51 UTC, jgphpc commented
cscs-ci run

2025-02-06 17:23 UTC, sekelle commented on domain/include/cstone/fields/field_states.hpp
>  #include <algorithm>
duplicate include

2025-02-06 17:35 UTC, nknk567 commented on domain/include/cstone/fields/field_states.hpp
>  #include <algorithm>
Yes, it was already added in the meantime :). Removed the duplicate.

2025-02-06 17:36 UTC, sekelle commented on main/src/sphexa/CMakeLists.txt
> +    target_link_libraries(${exename}-cuda PRIVATE disk_gpu)
`disk_gpu` should be linked to `propagator_gpu`

2025-02-06 17:39 UTC, sekelle commented on physics/Disk/include/accretion.hpp
> +    MPI_Reduce(star.removed_local.momentum.data(), p_removed_global.data(), 3, MpiType<double>{}, MPI_SUM, 0,
These `MPI_Reduces` can/should be combined into a single `MPI_Reduce` for better performance. Each call is latency bound, the combined call would be 4 times faster.

2025-02-06 17:41 UTC, sekelle commented on physics/Disk/include/accretion.hpp
> +    MPI_Bcast(&star.m, 1, MpiType<double>{}, 0, MPI_COMM_WORLD);
Should be combined: position_m1 + start.m -> local_buffer - > Bcast  -> local_buffer -> position_m1 + star.m

2025-02-07 09:25 UTC, sekelle requested changes
Please don't pass `ParticlesData` to compute functions. This will compromise maintainability of the code if we keep doing that. It's got all the data and if we use it everywhere then if we want to refactor `ParticlesData` then we need to change the whole code base. If passing the `x,y,z,m,` etc fields individually seems too cumbersome, you could create an argument pack struct which holds pointers (or `std::span`) to the required fields.

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/computeCentralForce_gpu.cu
> +    checkGpuErrors(cudaMalloc(reinterpret_cast<void**>(&force_device), sizeof *force_device));
You could use a __device__ symbol instead of a dynamic memory allocation, like we do in `sph/include/sph/hydro_ve/momentum_energy_gpu.cu`
It's faster and you won't have to free it afterwards.

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/computeCentralForce_gpu.cu
> +    checkGpuErrors(cudaMemcpy(force_device, &star.force_local, sizeof star.force_local, cudaMemcpyHostToDevice));
Would be a <<<1,1>>> kernel launch or memcpyToSymbol to initialize.

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/betaCooling_gpu.cu
> +template double duTimestepGPU(size_t, size_t, const sphexa::ParticlesData<cstone::GpuTag>&, const StarData&);
Are you planning to use multiple types of StarData?

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/exchangeStarPosition.hpp
> +    MPI_Bcast(star.position_m1.data(), 3, MpiType<double>{}, 0, MPI_COMM_WORLD);
Won't be needed with allreduce

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/removalStatistics.hpp
`removal_statistics.hpp`

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/exchangeStarPosition.hpp
`exchange_star.hpp` (?)

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/computeCentralForce_gpu.hpp
`central_force_gpu.h`

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/eos_polytropic_loop.hpp
`eos_polytropic_kern.hpp`

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/betaCooling_gpu.cu
`beta_cooling_gpu.cu`

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/betaCooling.hpp
`beta_cooling.hpp`

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/accretion_gpu.cu
> +#include <cub/cub.cuh>
`#include "cstone/cuda/cub.hpp` for compatibility with AMD/HIP

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/accretion_gpu.cu
> +#include "cuda_runtime.h"
`#include "cstone/cuda/cuda_runtime.hpp`

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/accretion_gpu.cu
> +template void computeAccretionConditionGPU(size_t, size_t, sphexa::ParticlesData<cstone::GpuTag>&, StarData&);
Are there more than one type of `StarData`?

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/include/exchangeStarPosition.hpp
> +    MPI_Reduce(star.force_local.data(), global_force.data(), 4, MpiType<double>{}, MPI_SUM, 0, MPI_COMM_WORLD);
You could turn this into an `Allreduce` and to the following computation on all ranks

2025-02-07 09:25 UTC, sekelle commented on physics/Disk/test/accretion.cpp
> +static void fill_grid(auto& x, auto& y, auto& z, double start, double end, size_t n_elements)
`fillGrid`

2025-02-07 09:26 UTC, sekelle commented on physics/Disk/include/accretion.hpp
> +    MPI_Reduce(star.removed_local.momentum.data(), p_removed_global.data(), 3, MpiType<double>{}, MPI_SUM, 0,
This could be turned into a single `allreduce` and following computation be done on all ranks

2025-02-07 09:28 UTC, sekelle commented on physics/Disk/include/betaCooling_gpu.cu
> +template double duTimestepGPU(size_t, size_t, const sphexa::ParticlesData<cstone::GpuTag>&, const StarData&);
If not, you don't need the template parameter.

2025-02-12 15:40 UTC, nknk567 commented on main/src/sphexa/CMakeLists.txt
> +    target_link_libraries(${exename}-cuda PRIVATE disk_gpu)
changed.

2025-02-12 15:41 UTC, nknk567 commented on physics/Disk/include/accretion.hpp
> +    MPI_Reduce(star.removed_local.momentum.data(), p_removed_global.data(), 3, MpiType<double>{}, MPI_SUM, 0,
The data is now copied to a buffer with one single MPI_Allreduce call.

2025-02-12 15:41 UTC, nknk567 commented on physics/Disk/include/computeCentralForce_gpu.cu
> +    checkGpuErrors(cudaMalloc(reinterpret_cast<void**>(&force_device), sizeof *force_device));
Changed

2025-02-12 15:42 UTC, nknk567 commented on physics/Disk/include/betaCooling_gpu.cu
> +template double duTimestepGPU(size_t, size_t, const sphexa::ParticlesData<cstone::GpuTag>&, const StarData&);
Removed the template parameter from the Cuda methods.

2025-02-12 15:43 UTC, nknk567 commented on physics/Disk/include/exchangeStarPosition.hpp
> +    MPI_Bcast(star.position_m1.data(), 3, MpiType<double>{}, 0, MPI_COMM_WORLD);
Removed the calls.

2025-02-12 15:44 UTC, nknk567 commented on physics/Disk/include/accretion_gpu.cu
> +template void computeAccretionConditionGPU(size_t, size_t, sphexa::ParticlesData<cstone::GpuTag>&, StarData&);
Removed template parameter from Cuda files.

2025-02-12 15:45 UTC, nknk567 commented on physics/Disk/include/eos_polytropic_loop.hpp
Removed the file, it's no longer needed.

2025-02-14 14:39 UTC, sekelle commented
Moved here:
https://github.com/sphexa-org/sphexa/pull/488

2025-02-14 14:39 UTC, closed without merging